#ifndef CMDLIST_H_
#define CMDLIST_H_

enum EN_CMDList{
	CMD_RESET_ERROR = 71,
	CMD_GET_ERR_GB = 72,
	CMD_RESET_ERR_GB = 73,
	CMD_GET_STATUS = 74,
	CMD_GET_ERR = 75,
	CMD_V3_SET = 1,
	CMD_V3_GET = 2,
	CMD_V4_SET = 3,
	CMD_V4_GET = 4,
	CMD_SET_GAS_PDE = 9,
	CMD_GET_GAS_PDE = 10,
	CMD_CLOSE_GAS_PDE = 11,
	CMD_STAT_GAS_PDE = 12,
	CMD_SET_GAS_AIR = 13,
	CMD_GET_GAS_AIR = 14,
	CMD_CLOSE_GAS_AIR = 15,
	CMD_STAT_GAS_AIR = 16,
	CMD_SET_GAS_O2 = 17,
	CMD_GET_GAS_O2 = 18,
	CMD_CLOSE_GAS_O2 = 19,
	CMD_STAT_GAS_O2 = 20,
	CMD_SET_GAS_4 = 21,
	CMD_GET_GAS_4 = 22,
	CMD_CLOSE_GAS_4 = 23,
	CMD_STAT_GAS_4 = 24,
	CMD_PUMP_SET = 25,
	CMD_PUMP_GET = 26,
	CMD_PUMP_GET_STA = 28,
	CMD_PUMP_GET_WAR = 30,
	CMD_PUMP_GET_ALA = 32,
	CMD_PUMP_GET_RMT = 34,

};

// Status byte your slave uses for “OK”
#define GB_STATUS_OK 0x80

// Wire-level command IDs — MUST match the gasbox slave protocol!

enum GB_CMDList{
	GB_CMD_SET_MFC1 = 0x02,
	GB_CMD_SET_MFC2 = 0x03,
	GB_CMD_SET_MFC3 = 0x04,
	GB_CMD_SET_MFC4 = 0x05,
	GB_CMD_GET_MFC1 = 0x06,
	GB_CMD_GET_MFC2 = 0x07,
	GB_CMD_GET_MFC3 = 0x08,
	GB_CMD_GET_MFC4 = 0x09,
	GB_CMD_VALVE3_CLOSE = 0x0A,
	GB_CMD_VALVE4_CLOSE = 0x0B,
	GB_CMD_VALVE3_OPEN = 0x0C,
	GB_CMD_VALVE4_OPEN = 0x0D,
	GB_CMD_VALVE3_GET = 0x0E,
	GB_CMD_VALVE4_GET = 0x0F,
	GB_CMD_GET_ERR = 0x10,
	GB_CMD_CLR_ERR = 0x11,
	GB_CMD_CLOSE_MFC1 = 0x12,
	GB_CMD_CLOSE_MFC2 = 0x13,
	GB_CMD_CLOSE_MFC3 = 0x14,
	GB_CMD_CLOSE_MFC4 = 0x15,
};

#endif /* CMDLIST_H_ */
